# Generated by Django 5.2.12 on 2026-04-09 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_announcement_inquiry'),
    ]

    operations = [
        migrations.AddField(
            model_name='inquiry',
            name='reply_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='title',
            field=models.CharField(default='제목 없음', max_length=255),
        ),
    ]
