# Generated by Django 5.2.12 on 2026-04-09 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_inquiry_reply_email_inquiry_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='is_selected_for_users',
            field=models.BooleanField(default=False),
        ),
    ]
