# Generated by Django 5.2.12 on 2026-04-02 03:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diet', '0002_meallog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolMealSelectionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('meal_type', models.CharField(choices=[('breakfast', 'Breakfast'), ('lunch', 'Lunch'), ('dinner', 'Dinner')], max_length=20)),
                ('menu_name', models.CharField(max_length=100)),
                ('selection', models.CharField(choices=[('none', 'None'), ('small', 'Small'), ('medium', 'Medium'), ('large', 'Large')], max_length=20)),
                ('estimated_protein_grams', models.DecimalField(decimal_places=1, max_digits=6)),
                ('final_protein_grams', models.DecimalField(decimal_places=1, max_digits=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='school_meal_selection_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['meal_type', 'menu_name'],
            },
        ),
    ]
