EXERCISE_CATALOG = [
    {'code': 'flying_chest_machine', 'name': '플라잉 체스트 머신', 'category': 'CHEST', 'target_muscle': '가슴'},
    {'code': 'chest_press_machine', 'name': '체스트 프레스 머신', 'category': 'CHEST', 'target_muscle': '가슴'},
    {'code': 'incline_press_machine', 'name': '인클라인 프레스 머신', 'category': 'CHEST', 'target_muscle': '상부 가슴'},
    {'code': 'barbell_bench_press', 'name': '바벨 벤치프레스', 'category': 'CHEST', 'target_muscle': '가슴'},
    {'code': 'dumbbell_bench_press', 'name': '덤벨 벤치프레스', 'category': 'CHEST', 'target_muscle': '가슴'},
    {'code': 'incline_dumbbell_press', 'name': '인클라인 덤벨 프레스', 'category': 'CHEST', 'target_muscle': '상부 가슴'},
    {'code': 'decline_dumbbell_press', 'name': '디클라인 덤벨 프레스', 'category': 'CHEST', 'target_muscle': '하부 가슴'},
    {'code': 'dumbbell_fly', 'name': '덤벨 플라이', 'category': 'CHEST', 'target_muscle': '가슴'},
    {'code': 'weighted_dips', 'name': '웨이티드 딥스', 'category': 'CHEST', 'target_muscle': '하부 가슴'},
    {'code': 'lat_pulldown', 'name': '랫풀다운', 'category': 'BACK', 'target_muscle': '광배근'},
    {'code': 'seated_row', 'name': '시티드 로우', 'category': 'BACK', 'target_muscle': '등'},
    {'code': 'assisted_pull_up', 'name': '어시스트 풀업', 'category': 'BACK', 'target_muscle': '광배근'},
    {'code': 'one_arm_dumbbell_row', 'name': '원암 덤벨 로우', 'category': 'BACK', 'target_muscle': '광배근'},
    {'code': 'barbell_bent_over_row', 'name': '바벨 벤트오버 로우', 'category': 'BACK', 'target_muscle': '등'},
    {'code': 'pendlay_row', 'name': '펜들레이 로우', 'category': 'BACK', 'target_muscle': '등'},
    {'code': 'pull_up', 'name': '풀업', 'category': 'BACK', 'target_muscle': '광배근'},
    {'code': 'chin_up', 'name': '친업', 'category': 'BACK', 'target_muscle': '광배근'},
    {'code': 'barbell_shrug', 'name': '바벨 슈러그', 'category': 'BACK', 'target_muscle': '승모근'},
    {'code': 'back_extension', 'name': '백 익스텐션', 'category': 'BACK', 'target_muscle': '척추기립근'},
    {'code': 'leg_press', 'name': '레그 프레스', 'category': 'LEGS', 'target_muscle': '하체'},
    {'code': 'leg_extension', 'name': '레그 익스텐션', 'category': 'LEGS', 'target_muscle': '대퇴사두근'},
    {'code': 'leg_curl', 'name': '레그 컬', 'category': 'LEGS', 'target_muscle': '햄스트링'},
    {'code': 'smith_squat', 'name': '스미스 스쿼트', 'category': 'LEGS', 'target_muscle': '하체'},
    {'code': 'barbell_back_squat', 'name': '바벨 백 스쿼트', 'category': 'LEGS', 'target_muscle': '하체'},
    {'code': 'front_squat', 'name': '프론트 스쿼트', 'category': 'LEGS', 'target_muscle': '대퇴사두근'},
    {'code': 'goblet_squat', 'name': '고블릿 스쿼트', 'category': 'LEGS', 'target_muscle': '하체'},
    {'code': 'box_squat', 'name': '박스 스쿼트', 'category': 'LEGS', 'target_muscle': '하체'},
    {'code': 'romanian_deadlift', 'name': '루마니안 데드리프트', 'category': 'LEGS', 'target_muscle': '햄스트링'},
    {'code': 'conventional_deadlift', 'name': '컨벤셔널 데드리프트', 'category': 'LEGS', 'target_muscle': '후면사슬'},
    {'code': 'clean_deadlift', 'name': '클린 데드리프트', 'category': 'LEGS', 'target_muscle': '후면사슬'},
    {'code': 'dumbbell_lunge', 'name': '덤벨 런지', 'category': 'LEGS', 'target_muscle': '하체'},
    {'code': 'bulgarian_split_squat', 'name': '불가리안 스플릿 스쿼트', 'category': 'LEGS', 'target_muscle': '하체'},
    {'code': 'barbell_hip_thrust', 'name': '바벨 힙 쓰러스트', 'category': 'LEGS', 'target_muscle': '둔근'},
    {'code': 'glute_drive', 'name': '글루트 드라이브', 'category': 'LEGS', 'target_muscle': '둔근'},
    {'code': 'calf_raise_machine', 'name': '카프 레이즈 머신', 'category': 'LEGS', 'target_muscle': '종아리'},
    {'code': 'shoulder_press_machine', 'name': '숄더 프레스 머신', 'category': 'SHOULDERS', 'target_muscle': '어깨'},
    {'code': 'lateral_raise_machine', 'name': '레터럴 레이즈 머신', 'category': 'SHOULDERS', 'target_muscle': '측면 삼각근'},
    {'code': 'dumbbell_shoulder_press', 'name': '덤벨 숄더 프레스', 'category': 'SHOULDERS', 'target_muscle': '어깨'},
    {'code': 'rear_delt_machine', 'name': '리어 델트 머신', 'category': 'SHOULDERS', 'target_muscle': '후면 삼각근'},
    {'code': 'barbell_overhead_press', 'name': '바벨 오버헤드 프레스', 'category': 'SHOULDERS', 'target_muscle': '어깨'},
    {'code': 'arnold_press', 'name': '아놀드 프레스', 'category': 'SHOULDERS', 'target_muscle': '어깨'},
    {'code': 'side_lateral_raise', 'name': '사이드 레터럴 레이즈', 'category': 'SHOULDERS', 'target_muscle': '측면 삼각근'},
    {'code': 'dumbbell_lateral_raise', 'name': '덤벨 레터럴 레이즈', 'category': 'SHOULDERS', 'target_muscle': '측면 삼각근'},
    {'code': 'dumbbell_rear_delt_fly', 'name': '덤벨 리어 델트 플라이', 'category': 'SHOULDERS', 'target_muscle': '후면 삼각근'},
    {'code': 'barbell_upright_row', 'name': '바벨 업라이트 로우', 'category': 'SHOULDERS', 'target_muscle': '승모근'},
    {'code': 'cable_pushdown', 'name': '케이블 푸시다운', 'category': 'ARMS', 'target_muscle': '삼두근'},
    {'code': 'dumbbell_curl', 'name': '덤벨 컬', 'category': 'ARMS', 'target_muscle': '이두근'},
    {'code': 'hammer_curl', 'name': '해머 컬', 'category': 'ARMS', 'target_muscle': '이두근'},
    {'code': 'preacher_curl', 'name': '프리처 컬', 'category': 'ARMS', 'target_muscle': '이두근'},
    {'code': 'overhead_triceps_extension', 'name': '오버헤드 트라이셉스 익스텐션', 'category': 'ARMS', 'target_muscle': '삼두근'},
    {'code': 'assisted_dips', 'name': '어시스트 딥스', 'category': 'ARMS', 'target_muscle': '삼두근'},
    {'code': 'ez_bar_curl', 'name': 'EZ바 컬', 'category': 'ARMS', 'target_muscle': '이두근'},
    {'code': 'incline_dumbbell_curl', 'name': '인클라인 덤벨 컬', 'category': 'ARMS', 'target_muscle': '이두근'},
    {'code': 'concentration_curl', 'name': '컨센트레이션 컬', 'category': 'ARMS', 'target_muscle': '이두근'},
    {'code': 'skull_crusher', 'name': '스컬 크러셔', 'category': 'ARMS', 'target_muscle': '삼두근'},
    {'code': 'dumbbell_kickback', 'name': '덤벨 킥백', 'category': 'ARMS', 'target_muscle': '삼두근'},
    {'code': 'reverse_curl', 'name': '리버스 컬', 'category': 'ARMS', 'target_muscle': '전완근'},
    {'code': 'close_grip_bench_press', 'name': '클로즈그립 벤치프레스', 'category': 'ARMS', 'target_muscle': '삼두근'},
    {'code': 'ab_crunch_machine', 'name': '앱 크런치 머신', 'category': 'ABS', 'target_muscle': '복근'},
    {'code': 'cable_crunch', 'name': '케이블 크런치', 'category': 'ABS', 'target_muscle': '복근'},
    {'code': 'hanging_leg_raise', 'name': '행잉 레그 레이즈', 'category': 'ABS', 'target_muscle': '하복부'},
    {'code': 'weighted_sit_up', 'name': '웨이티드 싯업', 'category': 'ABS', 'target_muscle': '복근'},
    {'code': 'ab_roll_out', 'name': 'ab 롤 아웃', 'category': 'ABS', 'target_muscle': '코어'},
    {'code': 'treadmill', 'name': '런닝머신', 'category': 'CARDIO', 'target_muscle': '유산소'},
    {'code': 'cycle', 'name': '사이클', 'category': 'CARDIO', 'target_muscle': '유산소'},
    {'code': 'elliptical', 'name': '일립티컬', 'category': 'CARDIO', 'target_muscle': '유산소'},
    {'code': 'rowing_machine', 'name': '로잉 머신', 'category': 'CARDIO', 'target_muscle': '유산소'},
    {'code': 'stability_training', 'name': '안정화 트레이닝', 'category': 'CARDIO', 'target_muscle': '퍼포먼스'},
    {'code': 'coordination_training', 'name': '협응력 트레이닝', 'category': 'CARDIO', 'target_muscle': '퍼포먼스'},
    {'code': 'lying_triceps_extension', 'name': '라잉 트라이셉스 익스텐션', 'category': 'ARMS', 'target_muscle': '삼두근'},
    {'code': 'cable_arm_pulldown', 'name': '케이블 암풀다운', 'category': 'BACK', 'target_muscle': '광배근'},
]
