# Generated by Django 5.2.12 on 2026-03-31 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('CHEST', '가슴'), ('BACK', '등'), ('LEGS', '하체'), ('SHOULDERS', '어깨'), ('ARMS', '팔'), ('ABS', '복근'), ('CARDIO', '유산소')], max_length=20)),
                ('target_muscle', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
