# Generated by Django 5.2.12 on 2026-04-07 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='code',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='exercise',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='category',
            field=models.CharField(choices=[('CHEST', '가슴'), ('BACK', '등'), ('LEGS', '하체'), ('SHOULDERS', '어깨'), ('ARMS', '팔'), ('ABS', '코어'), ('CARDIO', '유산소')], max_length=20),
        ),
    ]
