from django.urls import path
from rest_framework_simplejwt.views import TokenBlacklistView

from .views import (
    CustomTokenObtainPairView,
    DashboardView,
    GrassView,
    OnboardingCompleteView,
    OnboardingDraftView,
    PasswordChangeView,
    PushNotificationTestView,
    PushTokenView,
    SignupView,
    UserProfileView,
    AdminLoginView,
    AnnouncementListView,
    AdminAnnouncementView,
    AdminAnnouncementDetailView,
    InquiryView,
    AdminInquiryView,
    AdminInquiryDetailView,
    AdminInquiryDetailView,
    AdminLunchReminderRunView,
    AdminBreakfastReminderRunView,
    AdminDinnerReminderRunView,
    AdminExerciseReminderRunView,
)


urlpatterns = [
    path('auth/signup/', SignupView.as_view(), name='signup'),
    path('auth/login/', CustomTokenObtainPairView.as_view(), name='login'),
    path('auth/logout/', TokenBlacklistView.as_view(), name='logout'),
    path('me/', UserProfileView.as_view(), name='me'),
    path('me/profile/', UserProfileView.as_view(), name='profile_update'),
    path('me/dashboard/', DashboardView.as_view(), name='dashboard'),
    path('me/grass/', GrassView.as_view(), name='grass'),
    path('me/password/', PasswordChangeView.as_view(), name='password_change'),
    path('me/push-tokens', PushTokenView.as_view(), name='push_tokens_no_slash'),
    path('me/push-tokens/', PushTokenView.as_view(), name='push_tokens'),
    path('me/push-tokens/test', PushNotificationTestView.as_view(), name='push_tokens_test_no_slash'),
    path('me/push-tokens/test/', PushNotificationTestView.as_view(), name='push_tokens_test'),
    path('me/onboarding/draft/', OnboardingDraftView.as_view(), name='onboarding_draft'),
    path('me/onboarding/complete/', OnboardingCompleteView.as_view(), name='onboarding_complete'),
    
    path('auth/admin/login', AdminLoginView.as_view(), name='admin_login_no_slash'),
    path('auth/admin/login/', AdminLoginView.as_view(), name='admin_login'),
    path('announcements', AnnouncementListView.as_view(), name='announcements_no_slash'),
    path('announcements/', AnnouncementListView.as_view(), name='announcements'),
    path('admin/announcements', AdminAnnouncementView.as_view(), name='admin_announcements_no_slash'),
    path('admin/announcements/', AdminAnnouncementView.as_view(), name='admin_announcements'),
    path('admin/announcements/<int:pk>', AdminAnnouncementDetailView.as_view(), name='admin_announcements_detail_no_slash'),
    path('admin/announcements/<int:pk>/', AdminAnnouncementDetailView.as_view(), name='admin_announcements_detail'),
    path('me/inquiries', InquiryView.as_view(), name='me_inquiries_no_slash'),
    path('me/inquiries/', InquiryView.as_view(), name='me_inquiries'),
    path('admin/inquiries', AdminInquiryView.as_view(), name='admin_inquiries_no_slash'),
    path('admin/inquiries/', AdminInquiryView.as_view(), name='admin_inquiries'),
    path('admin/inquiries/<int:pk>', AdminInquiryDetailView.as_view(), name='admin_inquiries_detail_no_slash'),
    path('admin/inquiries/<int:pk>/', AdminInquiryDetailView.as_view(), name='admin_inquiries_detail'),
    path('admin/push/lunch-reminders/run', AdminLunchReminderRunView.as_view(), name='admin_lunch_reminder_run_no_slash'),
    path('admin/push/lunch-reminders/run/', AdminLunchReminderRunView.as_view(), name='admin_lunch_reminder_run'),
    path('admin/push/breakfast-reminders/run', AdminBreakfastReminderRunView.as_view(), name='admin_breakfast_reminder_run_no_slash'),
    path('admin/push/breakfast-reminders/run/', AdminBreakfastReminderRunView.as_view(), name='admin_breakfast_reminder_run'),
    path('admin/push/dinner-reminders/run', AdminDinnerReminderRunView.as_view(), name='admin_dinner_reminder_run_no_slash'),
    path('admin/push/dinner-reminders/run/', AdminDinnerReminderRunView.as_view(), name='admin_dinner_reminder_run'),
    path('admin/push/exercise-reminders/run', AdminExerciseReminderRunView.as_view(), name='admin_exercise_reminder_run_no_slash'),
    path('admin/push/exercise-reminders/run/', AdminExerciseReminderRunView.as_view(), name='admin_exercise_reminder_run'),
]
